# Generated by Django 3.0.4 on 2020-03-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20200326_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
